/**
 * EPUB 3 export.
 *
 * An EPUB is a ZIP with a fixed layout: an uncompressed `mimetype` entry
 * first, a `META-INF/container.xml` pointing at the package document, and the
 * content itself. Reading systems are far stricter than browsers — every
 * content file must be well-formed XHTML, so chapter HTML is rebuilt through
 * the XML DOM rather than string-patched.
 *
 * A legacy `toc.ncx` is emitted alongside the EPUB 3 `nav.xhtml` because
 * older devices (and Kindle conversion) still look for it.
 */
import JSZip from "jszip";
import type { Project, ProjectChapter } from "./app-store";

const XHTML_NS = "http://www.w3.org/1999/xhtml";
const EPUB_NS = "http://www.idpf.org/2007/ops";

/** Elements that never carry content and must be serialised self-closed. */
const STRIP_TAGS = new Set(["script", "style", "iframe", "object", "embed", "link", "meta"]);

/** Escapes text for use inside XML text nodes and attribute values. */
function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Removes anything a reading system should never execute. The manuscript can
 * contain model output derived from user-uploaded documents, so this runs on
 * every chapter regardless of where the HTML came from.
 */
function sanitize(root: Element) {
  const walk = (node: Element) => {
    for (const child of Array.from(node.children)) {
      if (STRIP_TAGS.has(child.tagName.toLowerCase())) {
        child.remove();
        continue;
      }
      for (const attr of Array.from(child.attributes)) {
        const name = attr.name.toLowerCase();
        const isUnsafeHref =
          (name === "href" || name === "src") && /^\s*(javascript|data):/i.test(attr.value);
        if (name.startsWith("on") || isUnsafeHref) {
          child.removeAttribute(attr.name);
        }
      }
      walk(child);
    }
  };
  walk(root);
}

/**
 * Converts a fragment of chapter HTML into a complete, well-formed XHTML
 * document. The fragment is parsed with the HTML parser (which repairs
 * unclosed tags) and then imported into a real XML document, so the
 * serialiser — not us — guarantees well-formedness.
 */
function buildXhtml(title: string, bodyHtml: string): string {
  const parsed = new DOMParser().parseFromString(`<body>${bodyHtml}</body>`, "text/html");
  sanitize(parsed.body);

  const doc = document.implementation.createDocument(XHTML_NS, "html", null);
  const html = doc.documentElement;
  html.setAttribute("xmlns:epub", EPUB_NS);
  html.setAttribute("lang", "en");

  const head = doc.createElementNS(XHTML_NS, "head");
  const titleEl = doc.createElementNS(XHTML_NS, "title");
  titleEl.textContent = title;
  const charset = doc.createElementNS(XHTML_NS, "meta");
  charset.setAttribute("charset", "utf-8");
  const css = doc.createElementNS(XHTML_NS, "link");
  css.setAttribute("rel", "stylesheet");
  css.setAttribute("type", "text/css");
  css.setAttribute("href", "style.css");
  head.append(charset, titleEl, css);

  const body = doc.createElementNS(XHTML_NS, "body");
  for (const node of Array.from(parsed.body.childNodes)) {
    body.appendChild(doc.importNode(node, true));
  }

  html.append(head, body);

  const serialized = new XMLSerializer().serializeToString(doc);
  return `<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html>\n${serialized}`;
}

/** Chapter ids come from `slugify`, but a manifest id must be XML-name safe. */
function manifestId(index: number): string {
  return `chapter-${String(index + 1).padStart(3, "0")}`;
}

/** Turns the project's design settings into the stylesheet readers apply. */
function buildStylesheet(project: Project): string {
  const ds = project.designSettings;
  const size = (value: string | undefined, fallback: string) => value || fallback;

  return `/* Generated by Writerdost AI. Reading systems may override these. */
html { font-size: 100%; }
body {
  font-family: Georgia, "Times New Roman", serif;
  line-height: ${size(ds?.lineHeight, "1.6")};
  margin: 0 5%;
  text-align: left;
  widows: 2;
  orphans: 2;
}
h1, h2, h3, h4 {
  font-family: Helvetica, Arial, sans-serif;
  line-height: 1.25;
  page-break-after: avoid;
  break-after: avoid;
}
h1 { font-size: ${size(ds?.h1Size, "2em")}; margin: 1.2em 0 0.6em; }
h2 { font-size: ${size(ds?.h2Size, "1.6em")}; margin: 1.2em 0 0.6em; }
h3 { font-size: ${size(ds?.h3Size, "1.3em")}; margin: 1em 0 0.4em; }
h4 { font-size: ${size(ds?.h4Size, "1.1em")}; margin: 1em 0 0.4em; }
p {
  font-size: ${size(ds?.pSize, "1em")};
  margin-top: ${size(ds?.paragraphBefore, "0")};
  margin-bottom: ${size(ds?.paragraphAfter, "0.8em")};
}
ul, ol { margin: 0.6em 0 0.9em 1.2em; }
li { margin-bottom: 0.35em; }
blockquote {
  margin: 1em 1.5em;
  padding-left: 0.9em;
  border-left: 3px solid #cccccc;
  font-style: italic;
}
code { font-family: "Courier New", monospace; font-size: 0.9em; }
hr { border: 0; border-top: 1px solid #cccccc; margin: 1.5em 0; }
img { max-width: 100%; height: auto; }
.title-block { text-align: center; margin-top: 25%; }
.title-block h1 { font-size: 2.4em; }
.title-block p { font-style: italic; color: #555555; }
nav#toc ol { list-style: none; margin-left: 0; padding-left: 0; }
nav#toc li { margin-bottom: 0.5em; }
`;
}

/** Builds a human-readable contents page for the `front-toc` placeholder. */
function buildTocPage(entries: Array<{ id: string; title: string }>): string {
  const items = entries
    .map((e) => `<li><a href="${e.id}.xhtml">${xmlEscape(e.title)}</a></li>`)
    .join("\n");
  return `<h1>Table of Contents</h1>\n<nav id="toc"><ol>\n${items}\n</ol></nav>`;
}

/** The EPUB 3 navigation document. Required by the spec. */
function buildNav(entries: Array<{ id: string; title: string }>): string {
  const items = entries
    .map((e) => `      <li><a href="${e.id}.xhtml">${xmlEscape(e.title)}</a></li>`)
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="${XHTML_NS}" xmlns:epub="${EPUB_NS}" lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>Table of Contents</title>
    <link rel="stylesheet" type="text/css" href="style.css"/>
  </head>
  <body>
    <nav epub:type="toc" id="toc">
      <h1>Table of Contents</h1>
      <ol>
${items}
      </ol>
    </nav>
  </body>
</html>`;
}

/** Legacy navigation map, for readers that predate EPUB 3. */
function buildNcx(title: string, uuid: string, entries: Array<{ id: string; title: string }>): string {
  const points = entries
    .map(
      (e, i) => `    <navPoint id="nav-${i + 1}" playOrder="${i + 1}">
      <navLabel><text>${xmlEscape(e.title)}</text></navLabel>
      <content src="${e.id}.xhtml"/>
    </navPoint>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="urn:uuid:${uuid}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle><text>${xmlEscape(title)}</text></docTitle>
  <navMap>
${points}
  </navMap>
</ncx>`;
}

/** The package document: metadata, manifest and reading order. */
function buildOpf(
  project: Project,
  uuid: string,
  entries: Array<{ id: string; title: string }>,
  author: string,
): string {
  const manifest = entries
    .map((e) => `    <item id="${e.id}" href="${e.id}.xhtml" media-type="application/xhtml+xml"/>`)
    .join("\n");
  const spine = entries.map((e) => `    <itemref idref="${e.id}"/>`).join("\n");
  const keywords = (project.seoKeywords || [])
    .filter(Boolean)
    .map((k) => `    <dc:subject>${xmlEscape(k)}</dc:subject>`)
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="en">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="book-id">urn:uuid:${uuid}</dc:identifier>
    <dc:title>${xmlEscape(project.title)}</dc:title>
    <dc:language>en</dc:language>
    <dc:creator>${xmlEscape(author)}</dc:creator>
    <dc:description>${xmlEscape(project.description || "")}</dc:description>
${keywords}
    <meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d{3}Z$/, "Z")}</meta>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="style" href="style.css" media-type="text/css"/>
${manifest}
  </manifest>
  <spine toc="ncx">
${spine}
  </spine>
</package>`;
}

/** Chapters that hold no real prose and should not become their own file. */
function isEmptyPlaceholder(chapter: ProjectChapter): boolean {
  const text = chapter.content.replace(/<[^>]*>/g, "").trim();
  return text.length === 0 || /Placeholder\.\s*Add content during Finish phase\.$/i.test(text);
}

/**
 * Builds the EPUB and returns it as a Blob. Separated from the download so it
 * can be tested, or later reused for a server-side export.
 */
export async function buildEpubBlob(project: Project, author = "Writerdost AI"): Promise<Blob> {
  const uuid =
    typeof crypto !== "undefined" && "randomUUID" in crypto
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(16).slice(2)}`;

  const zip = new JSZip();

  // The mimetype entry must be first and stored uncompressed.
  zip.file("mimetype", "application/epub+zip", { compression: "STORE" });

  zip.file(
    "META-INF/container.xml",
    `<?xml version="1.0" encoding="utf-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`,
  );

  const oebps = zip.folder("OEBPS");
  if (!oebps) throw new Error("Could not create the EPUB content folder.");

  // A title page always leads, then every chapter that carries real content.
  const source = (project.chapters || []).filter(
    (chapter) => chapter.id !== "front-title" && !isEmptyPlaceholder(chapter),
  );

  const entries = [
    { id: "titlepage", title: project.title },
    ...source.map((chapter, index) => ({
      id: manifestId(index),
      title: chapter.title,
      chapter,
    })),
  ];

  // The reader-facing contents list covers the chapters, not the title page.
  const navEntries = entries.slice(1).map((e) => ({ id: e.id, title: e.title }));

  oebps.file("style.css", buildStylesheet(project));
  oebps.file("nav.xhtml", buildNav(navEntries));
  oebps.file("toc.ncx", buildNcx(project.title, uuid, navEntries));
  oebps.file("content.opf", buildOpf(project, uuid, entries, author));

  oebps.file(
    "titlepage.xhtml",
    buildXhtml(
      project.title,
      `<div class="title-block"><h1>${xmlEscape(project.title)}</h1>` +
        `<p>${xmlEscape(author)}</p></div>`,
    ),
  );

  for (const entry of entries.slice(1)) {
    const chapter = (entry as { chapter: ProjectChapter }).chapter;
    // The placeholder contents page becomes a real, linked one.
    const body =
      chapter.id === "front-toc" ? buildTocPage(navEntries.filter((n) => n.id !== entry.id)) : chapter.content;
    oebps.file(`${entry.id}.xhtml`, buildXhtml(chapter.title, body));
  }

  return zip.generateAsync({
    type: "blob",
    mimeType: "application/epub+zip",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
}

/** Generates the EPUB and triggers a browser download. */
export async function downloadEpub(project: Project, author?: string) {
  const blob = await buildEpubBlob(project, author);
  const url = URL.createObjectURL(blob);
  const element = document.createElement("a");

  element.setAttribute("href", url);
  element.setAttribute("download", `${project.title.replace(/\s+/g, "_")}.epub`);

  element.style.display = "none";
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);

  URL.revokeObjectURL(url);
}
